export const actionTypes = {
  ADD_COMMENT: 'COMMENTS/ADD_COMMENT',
  DELETE_COMMENT: 'COMMENTS/DELETE_COMMENT',
  SET_COMMENTS: 'COMMENTS/SET',
  SET_LOADING: 'COMMENTS/SET_LOADING',
  UPDATE_COMMENT: 'COMMENTS/UPDATE_COMMENT'
}
