export const actionTypes = {
  ADD_POST: 'COMMENTS/ADD_POST',
  DELETE_POST: 'POSTS/DELETE_POST',
  SET_LOADING: 'POSTS/SET_LOADING',
  SET_POST: 'POSTS/SET_POST',
  SET_POSTS: 'POSTS/SET_POSTS',
  UPDATE_POST: 'POSTS/UPDATE_POST',
  UPDATE_SCORE: 'POSTS/UPDATE_SCORE'
}
